# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace   # 删除行尾空格
    - id: end-of-file-fixer     # 确保文件以换行符结束
    - id: check-yaml            # 校验YAML语法

-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        # (可选) 指定 black 应该运行在哪个 Python 版本
        # language_version: python3.10
        args: [--line-length=120]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
    -   id: ruff
        args: [
            --fix,
            --exit-non-zero-on-fix,
            --select, "I,E,F,W",
            --line-length=120,
            ]
