KSANA_DIFFUSION_MODEL = "KSANA_DIFFUSION_MODEL"
KSANA_LORA = "KSANA_LORA"
KSANA_VAE_MODEL = "KSANA_VAE_MODEL"
KSANA_VACE_MODEL = "KSANA_VACE_MODEL"

KSANA_VAE_ENCODE_OUTPUT = "KSANA_VAE_ENCODE_OUTPUT"
KSANA_GENERATE_OUTPUT = "KSANA_GENERATE_OUTPUT"
KSANA_TEXT_ENCODE_OUTPUT = "CONDITIONING"

KSANA_ATTENTION_CONFIG = "KSANA_ATTENTION_CONFIG"
KSANA_CACHE_CONFIG = "KSANA_CACHE_CONFIG"
KSANA_TORCH_COMPILE = "KSANA_TORCH_COMPILE"
KSANA_VIDEO_CONTROL_CONFIG = "KSANA_VIDEO_CONTROL_CONFIG"

KSANA_SLG_ARGS = "KSANA_SLG_ARGS"
KSANA_FETA_ARGS = "KSANA_FETA_ARGS"
KSANA_EXPERIMENTAL_ARGS = "KSANA_EXPERIMENTAL_ARGS"
KSANA_VACE_EMBEDS = "KSANA_VACE_EMBEDS"

# WanVideoWrapper compatible types (for cross-project compatibility)
WANVIDEO_SLG_ARGS = "SLGARGS"
WANVIDEO_FETA_ARGS = "FETAARGS"
WANVIDEO_EXPERIMENTAL_ARGS = "EXPERIMENTALARGS"

KSANA_CATEGORY_LORA = "ksana/lora"
KSANA_CATEGORY_CACHE = "ksana/cache"
KSANA_CATEGORY_VAE = "ksana/vae"
KSANA_CATEGORY_UTILS = "ksana/utils"
KSANA_CATEGORY_CONFIGS = "ksana/configs"
