KSANA_DIFFUSION_MODEL = "KSANA_DIFFUSION_MODEL"
KSANA_LORA = "KSANA_LORA"
KSANA_VAE_MODEL = "KSANA_VAE_MODEL"

KSANA_VAE_ENCODE_OUTPUT = "KSANA_VAE_ENCODE_OUTPUT"
KSANA_GENERATE_OUTPUT = "KSANA_GENERATE_OUTPUT"
KSANA_TEXT_ENCODE_OUTPUT = "CONDITIONING"

KSANA_CACHE_CONFIG = "KSANA_CACHE_CONFIG"
KSANA_TORCH_COMPILE = "KSANA_TORCH_COMPILE"

KSANA_CATEGORY_LORA = "ksana/lora"
KSANA_CATEGORY_CACHE = "ksana/cache"
KSANA_CATEGORY_VAE = "ksana/vae"
KSANA_CATEGORY_UTILS = "ksana/utils"
