DEFAULT_RUN_DTYPE = "float16"
DEFAULT_OUTPUTS_VIDEO_DIR = "outputs"
DEFAULT_SEED = 42
DEFAULT_OFFLOAD_MODEL = False
DEFAULT_CACHE_METHOD = "DCache"
DEFAULT_SAVE_VIDEO = True
DEFAULT_RETURN_FRAMES = True
